const EXERCISES = [
  {
    "id": 1,
    "name": "Bent-Over Overhead Press (wyciskanie sprzed klatki nad głowę) RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=PnFU9f1i2tU",
    "isYoutube": true,
    "videoId": "PnFU9f1i2tU",
    "start": 0,
    "done": false
  },
  {
    "id": 2,
    "name": "Bent-Over Overhead Press (wyciskanie sprzed klatki nad głowę) GUMA ROZCIAGNIETA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=PnFU9f1i2tU",
    "isYoutube": true,
    "videoId": "PnFU9f1i2tU",
    "start": 0,
    "done": false
  },
  {
    "id": 3,
    "name": "Overhead Shoulder Press z Pull-Apart (wyciśnięcie nad głową i rozciągnięcie wtedy) oburącz RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Mw5C4WTHEVE&t=852s",
    "isYoutube": true,
    "videoId": "Mw5C4WTHEVE",
    "start": 852,
    "done": false
  },
  {
    "id": 4,
    "name": "to samo co 48 tylko z tyłu",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": null,
    "isYoutube": false,
    "videoId": null,
    "start": 0,
    "done": false
  },
  {
    "id": 5,
    "name": "Standing Lat Pulldown (ściąganie za plecy) z guma nad głową RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=sdft3ga7Hx0&t=203s",
    "isYoutube": true,
    "videoId": "sdft3ga7Hx0",
    "start": 203,
    "done": false
  },
  {
    "id": 6,
    "name": "Standing Lat Pulldown (ściąganie za plecy) z guma nad głową GUMA ROZCIĄGNIĘTA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=sdft3ga7Hx0&t=203s",
    "isYoutube": true,
    "videoId": "sdft3ga7Hx0",
    "start": 203,
    "done": false
  },
  {
    "id": 7,
    "name": "Mini Band Overhead Reach (unoszenie oburącz od pasa nad głowę) RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=3VAu6Lc5jfc",
    "isYoutube": true,
    "videoId": "3VAu6Lc5jfc",
    "start": 0,
    "done": false
  },
  {
    "id": 8,
    "name": "Mini Band Overhead Reach (unoszenie oburącz od pasa nad głowę) GUMA ROZCIAGNIETA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=3VAu6Lc5jfc",
    "isYoutube": true,
    "videoId": "3VAu6Lc5jfc",
    "start": 0,
    "done": false
  },
  {
    "id": 9,
    "name": "Band Front Pull-Apart Pulses (pulsy z rozciaganiem gumy nad głową) oburącz RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=_xrAGY9ST4g&t=392s",
    "isYoutube": true,
    "videoId": "_xrAGY9ST4g",
    "start": 392,
    "done": false
  },
  {
    "id": 10,
    "name": "Band Front Pull-Apart Pulses (pulsy z rozciaganiem gumy nad głową) oburącz GUMA ROZCIĄGNIĘTA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=_xrAGY9ST4g&t=392s",
    "isYoutube": true,
    "videoId": "_xrAGY9ST4g",
    "start": 392,
    "done": false
  },
  {
    "id": 11,
    "name": "Shoulder Press + Lat Pulldown Combo (wyciśnięcie sprzed i sciagniecie za głowę) RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Mw5C4WTHEVE&t=208s",
    "isYoutube": true,
    "videoId": "Mw5C4WTHEVE",
    "start": 208,
    "done": false
  },
  {
    "id": 12,
    "name": "Shoulder Press + Lat Pulldown Combo (wyciśnięcie sprzed i sciagniecie za głowę) GUMA ROZCIĄGNIĘTA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Mw5C4WTHEVE&t=208s",
    "isYoutube": true,
    "videoId": "Mw5C4WTHEVE",
    "start": 208,
    "done": false
  },
  {
    "id": 13,
    "name": "Lateral Raise Behind The Back - RĘCE SZEROKO Z TYŁU RĘCE WEWNĄTRZ GUMY (inaczej: rear arm extensions tez sie nazywa)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": null,
    "isYoutube": false,
    "videoId": null,
    "start": 0,
    "done": false
  },
  {
    "id": 14,
    "name": "Lateral Raise Behind The Back - RĘCE SZEROKO Z TYŁU GUMA ROZCIĄGANA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": null,
    "isYoutube": false,
    "videoId": null,
    "start": 0,
    "done": false
  },
  {
    "id": 15,
    "name": "Mini Band Push-Up",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=nRWlyfYfRjg",
    "isYoutube": true,
    "videoId": "nRWlyfYfRjg",
    "start": 0,
    "done": false
  },
  {
    "id": 16,
    "name": "Pompki eksplozywne z podbiciem z obu rąk",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": null,
    "isYoutube": false,
    "videoId": null,
    "start": 0,
    "done": false
  },
  {
    "id": 17,
    "name": "Mini Band Pushup with Hip Extension (pompka z uniesieniem jednej nogi gdy zejscie w dół)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtrainfitness.com/24-mini-band-exercises-chest-back-shoulders-arms-core-glutes-hips-legs-ankles-balance-workout/",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 18,
    "name": "Pozycja jak plank, proste ręce - out-in",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=yCTo7Hs03mo&t=189s",
    "isYoutube": true,
    "videoId": "yCTo7Hs03mo",
    "start": 189,
    "done": false
  },
  {
    "id": 19,
    "name": "Pozycja jak plank, proste ręce -  up-back",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": null,
    "isYoutube": false,
    "videoId": null,
    "start": 0,
    "done": false
  },
  {
    "id": 20,
    "name": "Plank Row",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/shorts/y607cXwLs7w",
    "isYoutube": true,
    "videoId": "y607cXwLs7w",
    "start": 0,
    "done": false
  },
  {
    "id": 21,
    "name": "Standing Chest Press (wyciśnięcie przed klatka) z guma wokół ramienia",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=sdft3ga7Hx0&t=476s",
    "isYoutube": true,
    "videoId": "sdft3ga7Hx0",
    "start": 476,
    "done": false
  },
  {
    "id": 22,
    "name": "Band External Rotations (rozciąganie na boki - guma złapana)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=_UvmPNGtlPM",
    "isYoutube": true,
    "videoId": "_UvmPNGtlPM",
    "start": 0,
    "done": false
  },
  {
    "id": 23,
    "name": "Band External Rotations (rozciąganie na boki - guma złapana) - TO SAMO JEDNORĄCZ",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=_UvmPNGtlPM",
    "isYoutube": true,
    "videoId": "_UvmPNGtlPM",
    "start": 0,
    "done": false
  },
  {
    "id": 24,
    "name": "Band External Rotations (rozciąganie na boki - nadgarstki w gumie od wewnątrz))",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=_UvmPNGtlPM",
    "isYoutube": true,
    "videoId": "_UvmPNGtlPM",
    "start": 0,
    "done": false
  },
  {
    "id": 25,
    "name": "Band External Rotations (rozciąganie na boki - nadgarstki w gumie od wewnątrz) - TO SAMO JEDNORĄCZ",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=_UvmPNGtlPM",
    "isYoutube": true,
    "videoId": "_UvmPNGtlPM",
    "start": 0,
    "done": false
  },
  {
    "id": 26,
    "name": "Rozciaganie gumy do zewnatrz na wysokosci łokci (szeroko, łopatki do siebie)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=UuM26K0Qeis&t=320s",
    "isYoutube": true,
    "videoId": "UuM26K0Qeis",
    "start": 320,
    "done": false
  },
  {
    "id": 27,
    "name": "Single Arm Overhead Shaper (rotacja ramienia nad głową jednoracz) z bandem",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Mw5C4WTHEVE&t=791s",
    "isYoutube": true,
    "videoId": "Mw5C4WTHEVE",
    "start": 791,
    "done": false
  },
  {
    "id": 28,
    "name": "Banded scapular retraction RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.tiktok.com/@schtory_time/video/7478430360519314730",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 29,
    "name": "Banded scapular retraction GUMA ROZCIĄGNIĘTA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.tiktok.com/@schtory_time/video/7478430360519314730",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 30,
    "name": "Banded overhead scapular retraction RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.tiktok.com/@schtory_time/video/7478430360519314730",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 31,
    "name": "Banded overhead scapular retraction GUMA ROZCIĄGNIĘTA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.tiktok.com/@schtory_time/video/7478430360519314730",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 32,
    "name": "Shoulder driver",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.tiktok.com/@theprehabguys/video/7251292069937958187",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 33,
    "name": "Quadruped Wall Clock",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.tiktok.com/@theprehabguys/video/7251292069937958187",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 34,
    "name": "Bent Raise + High Row Combo (unoszenie jak hantli bokiem)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Mw5C4WTHEVE&t=529s",
    "isYoutube": true,
    "videoId": "Mw5C4WTHEVE",
    "start": 529,
    "done": false
  },
  {
    "id": 35,
    "name": "Single Arm Lateral Raise (unoszenie boczne jednorecz) JEDNA RĘKA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Mw5C4WTHEVE&t=134s",
    "isYoutube": true,
    "videoId": "Mw5C4WTHEVE",
    "start": 134,
    "done": false
  },
  {
    "id": 36,
    "name": "Mini Band Back Row (wiosłowanie o stope)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtrainfitness.com/24-mini-band-exercises-chest-back-shoulders-arms-core-glutes-hips-legs-ankles-balance-workout/",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 37,
    "name": "Mini Band Biceps Curl (stojąc)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtrainfitness.com/24-mini-band-exercises-chest-back-shoulders-arms-core-glutes-hips-legs-ankles-balance-workout/",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 38,
    "name": "Half-Kneeling Bicep Curl (uginanie ramienia w polklęku) z guma pod stopa",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=sdft3ga7Hx0&t=267s",
    "isYoutube": true,
    "videoId": "sdft3ga7Hx0",
    "start": 267,
    "done": false
  },
  {
    "id": 39,
    "name": "Mini Band Triceps Pushdown",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtrainfitness.com/24-mini-band-exercises-chest-back-shoulders-arms-core-glutes-hips-legs-ankles-balance-workout/",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 40,
    "name": "Standing Narrow Tricep Extension (wąski wyprost triceps) z guma - druga wersja 71 (tam bokiem, tu prosto)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=sdft3ga7Hx0&t=420s",
    "isYoutube": true,
    "videoId": "sdft3ga7Hx0",
    "start": 420,
    "done": false
  },
  {
    "id": 41,
    "name": "Triceps tyłem (do góry)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=sdft3ga7Hx0&t=572s",
    "isYoutube": true,
    "videoId": "sdft3ga7Hx0",
    "start": 572,
    "done": false
  },
  {
    "id": 42,
    "name": "Triceps tyłem (do dołu)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=sdft3ga7Hx0&t=572s",
    "isYoutube": true,
    "videoId": "sdft3ga7Hx0",
    "start": 572,
    "done": false
  },
  {
    "id": 43,
    "name": "Low Pull-Apart (rozciąganie gumy nisko) - początkujący",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Lk5PisETE9I&t=144s",
    "isYoutube": true,
    "videoId": "Lk5PisETE9I",
    "start": 144,
    "done": false
  },
  {
    "id": 44,
    "name": "Double Lateral Triceps Extension (wyprost triceps obiema rękami) TRUDNIEJSZA WERSJA 82",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=H78qhvplQFU&t=797s",
    "isYoutube": true,
    "videoId": "H78qhvplQFU",
    "start": 797,
    "done": false
  },
  {
    "id": 45,
    "name": "Lateral Triceps Extension (wyprost triceps na boki)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=H78qhvplQFU&t=85s",
    "isYoutube": true,
    "videoId": "H78qhvplQFU",
    "start": 85,
    "done": false
  },
  {
    "id": 46,
    "name": "Straight Arm Pulse Raise (pulsujące unoszenie prostej ręki) z bandem",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=e90l8zQtXbc&t=254s",
    "isYoutube": true,
    "videoId": "e90l8zQtXbc",
    "start": 254,
    "done": false
  },
  {
    "id": 47,
    "name": "Lat pull down",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Mw5C4WTHEVE&t=240s",
    "isYoutube": true,
    "videoId": "Mw5C4WTHEVE",
    "start": 240,
    "done": false
  },
  {
    "id": 48,
    "name": "Archer Row / T-Row (wiosłowanie typu \"lucznik\") - TO CO 23 STOJĄC",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=H78qhvplQFU&t=1114s",
    "isYoutube": true,
    "videoId": "H78qhvplQFU",
    "start": 1114,
    "done": false
  },
  {
    "id": 49,
    "name": "Half-Kneeling Archer Row",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=B6bAgIz9uFw",
    "isYoutube": true,
    "videoId": "B6bAgIz9uFw",
    "start": 0,
    "done": false
  },
  {
    "id": 50,
    "name": "Serve the Platter (unoszenie ręki jak z tacka) z bandem",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=e90l8zQtXbc&t=463s",
    "isYoutube": true,
    "videoId": "e90l8zQtXbc",
    "start": 463,
    "done": false
  },
  {
    "id": 51,
    "name": "SeatedRow - \"Teros\" (wiosłowanie oburącz) - RĘCE WEWNĄTRZ",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=DPZJ_HuF6lE&t=1260s",
    "isYoutube": true,
    "videoId": "DPZJ_HuF6lE",
    "start": 1260,
    "done": false
  },
  {
    "id": 52,
    "name": "SeatedRow - \"Teros\" (wiosłowanie oburącz) - GUMA ROZCIĄGNIĘTA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=DPZJ_HuF6lE&t=1260s",
    "isYoutube": true,
    "videoId": "DPZJ_HuF6lE",
    "start": 1260,
    "done": false
  },
  {
    "id": 53,
    "name": "Single Arm Row (wiosłowanie jednorecz) z bandem zaczepionym o stopę",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=_xrAGY9ST4g&t=518s",
    "isYoutube": true,
    "videoId": "_xrAGY9ST4g",
    "start": 518,
    "done": false
  },
  {
    "id": 54,
    "name": "Mini Band Wall Slide - SIŁOWNIA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Silownia",
    "link": "https://www.youtube.com/shorts/wAb_LNjfnIw",
    "isYoutube": true,
    "videoId": "wAb_LNjfnIw",
    "start": 0,
    "done": false
  },
  {
    "id": 55,
    "name": "Mini Band Wall Slide tyłem - SIŁOWNIA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Silownia",
    "link": "https://www.youtube.com/watch?v=wLlqzWMHrXI",
    "isYoutube": true,
    "videoId": "wLlqzWMHrXI",
    "start": 0,
    "done": false
  },
  {
    "id": 56,
    "name": "Wall clock SIŁOWNIA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Silownia",
    "link": "https://www.tiktok.com/@theprehabguys/video/7251292069937958187",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 57,
    "name": "Spider crawls SIŁOWNIA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Silownia",
    "link": "https://www.tiktok.com/@make.it.train/video/7313010368345885995",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 58,
    "name": "1 SIŁOWNIA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Silownia",
    "link": "https://www.tiktok.com/@fizjoboryss/video/7623838617907121441",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 59,
    "name": "2 SIŁOWNIA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Silownia",
    "link": "https://www.tiktok.com/@fizjoboryss/video/7623838617907121441",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 60,
    "name": "3 SIŁOWNIA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Silownia",
    "link": "https://www.tiktok.com/@fizjoboryss/video/7623838617907121441",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  }
];
