const EXERCISES = [
  {
    "id": 1,
    "name": "Bent-Over Overhead Press (wyciskanie sprzed klatki nad głowę) RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=PnFU9f1i2tU",
    "isYoutube": true,
    "videoId": "PnFU9f1i2tU",
    "start": 0,
    "done": false
  },
  {
    "id": 2,
    "name": "Bent-Over Overhead Press (wyciskanie sprzed klatki nad głowę) GUMA ROZCIAGNIETA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=PnFU9f1i2tU",
    "isYoutube": true,
    "videoId": "PnFU9f1i2tU",
    "start": 0,
    "done": false
  },
  {
    "id": 3,
    "name": "Overhead Shoulder Press z Pull-Apart (wyciśnięcie nad głową i rozciągnięcie wtedy) oburącz RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Mw5C4WTHEVE&t=852s",
    "isYoutube": true,
    "videoId": "Mw5C4WTHEVE",
    "start": 852,
    "done": false
  },
  {
    "id": 4,
    "name": "to samo co 48 tylko z tyłu",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": null,
    "isYoutube": false,
    "videoId": null,
    "start": 0,
    "done": false
  },
  {
    "id": 5,
    "name": "Standing Lat Pulldown (ściąganie za plecy) z guma nad głową RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=sdft3ga7Hx0&t=203s",
    "isYoutube": true,
    "videoId": "sdft3ga7Hx0",
    "start": 203,
    "done": false
  },
  {
    "id": 6,
    "name": "Standing Lat Pulldown (ściąganie za plecy) z guma nad głową GUMA ROZCIĄGNIĘTA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=sdft3ga7Hx0&t=203s",
    "isYoutube": true,
    "videoId": "sdft3ga7Hx0",
    "start": 203,
    "done": false
  },
  {
    "id": 7,
    "name": "Mini Band Overhead Reach (unoszenie oburącz od pasa nad głowę) RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=3VAu6Lc5jfc",
    "isYoutube": true,
    "videoId": "3VAu6Lc5jfc",
    "start": 0,
    "done": false
  },
  {
    "id": 8,
    "name": "Mini Band Overhead Reach (unoszenie oburącz od pasa nad głowę) GUMA ROZCIAGNIETA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=3VAu6Lc5jfc",
    "isYoutube": true,
    "videoId": "3VAu6Lc5jfc",
    "start": 0,
    "done": false
  },
  {
    "id": 9,
    "name": "Band Front Pull-Apart Pulses (pulsy z rozciaganiem gumy nad głową) oburącz RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=_xrAGY9ST4g&t=392s",
    "isYoutube": true,
    "videoId": "_xrAGY9ST4g",
    "start": 392,
    "done": false
  },
  {
    "id": 10,
    "name": "Band Front Pull-Apart Pulses (pulsy z rozciaganiem gumy nad głową) oburącz GUMA ROZCIĄGNIĘTA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=_xrAGY9ST4g&t=392s",
    "isYoutube": true,
    "videoId": "_xrAGY9ST4g",
    "start": 392,
    "done": false
  },
  {
    "id": 11,
    "name": "Shoulder Press + Lat Pulldown Combo (wyciśnięcie sprzed i sciagniecie za głowę) RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Mw5C4WTHEVE&t=208s",
    "isYoutube": true,
    "videoId": "Mw5C4WTHEVE",
    "start": 208,
    "done": false
  },
  {
    "id": 12,
    "name": "Shoulder Press + Lat Pulldown Combo (wyciśnięcie sprzed i sciagniecie za głowę) GUMA ROZCIĄGNIĘTA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Mw5C4WTHEVE&t=208s",
    "isYoutube": true,
    "videoId": "Mw5C4WTHEVE",
    "start": 208,
    "done": false
  },
  {
    "id": 13,
    "name": "Lateral Raise Behind The Back - RĘCE SZEROKO Z TYŁU RĘCE WEWNĄTRZ GUMY (inaczej: rear arm extensions tez sie nazywa)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": null,
    "isYoutube": false,
    "videoId": null,
    "start": 0,
    "done": false
  },
  {
    "id": 14,
    "name": "Lateral Raise Behind The Back - RĘCE SZEROKO Z TYŁU GUMA ROZCIĄGANA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": null,
    "isYoutube": false,
    "videoId": null,
    "start": 0,
    "done": false
  },
  {
    "id": 15,
    "name": "Mini Band Push-Up",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=nRWlyfYfRjg",
    "isYoutube": true,
    "videoId": "nRWlyfYfRjg",
    "start": 0,
    "done": false
  },
  {
    "id": 16,
    "name": "Pompki eksplozywne z podbiciem z obu rąk",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": null,
    "isYoutube": false,
    "videoId": null,
    "start": 0,
    "done": false
  },
  {
    "id": 17,
    "name": "Mini Band Pushup with Hip Extension (pompka z uniesieniem jednej nogi gdy zejscie w dół)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtrainfitness.com/24-mini-band-exercises-chest-back-shoulders-arms-core-glutes-hips-legs-ankles-balance-workout/",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 18,
    "name": "Pozycja jak plank, proste ręce - out-in",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=yCTo7Hs03mo&t=189s",
    "isYoutube": true,
    "videoId": "yCTo7Hs03mo",
    "start": 189,
    "done": false
  },
  {
    "id": 19,
    "name": "Pozycja jak plank, proste ręce -  up-back",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": null,
    "isYoutube": false,
    "videoId": null,
    "start": 0,
    "done": false
  },
  {
    "id": 20,
    "name": "Plank Row",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/shorts/y607cXwLs7w",
    "isYoutube": true,
    "videoId": "y607cXwLs7w",
    "start": 0,
    "done": false
  },
  {
    "id": 21,
    "name": "Standing Chest Press (wyciśnięcie przed klatka) z guma wokół ramienia",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=sdft3ga7Hx0&t=476s",
    "isYoutube": true,
    "videoId": "sdft3ga7Hx0",
    "start": 476,
    "done": false
  },
  {
    "id": 22,
    "name": "Band External Rotations (rozciąganie na boki - guma złapana)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=_UvmPNGtlPM",
    "isYoutube": true,
    "videoId": "_UvmPNGtlPM",
    "start": 0,
    "done": false
  },
  {
    "id": 23,
    "name": "Band External Rotations (rozciąganie na boki - guma złapana) - TO SAMO JEDNORĄCZ",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=_UvmPNGtlPM",
    "isYoutube": true,
    "videoId": "_UvmPNGtlPM",
    "start": 0,
    "done": false
  },
  {
    "id": 24,
    "name": "Band External Rotations (rozciąganie na boki - nadgarstki w gumie od wewnątrz))",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=_UvmPNGtlPM",
    "isYoutube": true,
    "videoId": "_UvmPNGtlPM",
    "start": 0,
    "done": false
  },
  {
    "id": 25,
    "name": "Band External Rotations (rozciąganie na boki - nadgarstki w gumie od wewnątrz) - TO SAMO JEDNORĄCZ",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=_UvmPNGtlPM",
    "isYoutube": true,
    "videoId": "_UvmPNGtlPM",
    "start": 0,
    "done": false
  },
  {
    "id": 26,
    "name": "Rozciaganie gumy do zewnatrz na wysokosci łokci (szeroko, łopatki do siebie)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=UuM26K0Qeis&t=320s",
    "isYoutube": true,
    "videoId": "UuM26K0Qeis",
    "start": 320,
    "done": false
  },
  {
    "id": 27,
    "name": "Single Arm Overhead Shaper (rotacja ramienia nad głową jednoracz) z bandem",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Mw5C4WTHEVE&t=791s",
    "isYoutube": true,
    "videoId": "Mw5C4WTHEVE",
    "start": 791,
    "done": false
  },
  {
    "id": 28,
    "name": "Banded scapular retraction RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.tiktok.com/@schtory_time/video/7478430360519314730",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 29,
    "name": "Banded scapular retraction GUMA ROZCIĄGNIĘTA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.tiktok.com/@schtory_time/video/7478430360519314730",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 30,
    "name": "Banded overhead scapular retraction RĘCE WEWNĄTRZ GUMY",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.tiktok.com/@schtory_time/video/7478430360519314730",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 31,
    "name": "Banded overhead scapular retraction GUMA ROZCIĄGNIĘTA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.tiktok.com/@schtory_time/video/7478430360519314730",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 32,
    "name": "Shoulder driver",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.tiktok.com/@theprehabguys/video/7251292069937958187",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 33,
    "name": "Quadruped Wall Clock",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.tiktok.com/@theprehabguys/video/7251292069937958187",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 34,
    "name": "Bent Raise + High Row Combo (unoszenie jak hantli bokiem)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Mw5C4WTHEVE&t=529s",
    "isYoutube": true,
    "videoId": "Mw5C4WTHEVE",
    "start": 529,
    "done": false
  },
  {
    "id": 35,
    "name": "Single Arm Lateral Raise (unoszenie boczne jednorecz) JEDNA RĘKA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Mw5C4WTHEVE&t=134s",
    "isYoutube": true,
    "videoId": "Mw5C4WTHEVE",
    "start": 134,
    "done": false
  },
  {
    "id": 36,
    "name": "Mini Band Back Row (wiosłowanie o stope)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtrainfitness.com/24-mini-band-exercises-chest-back-shoulders-arms-core-glutes-hips-legs-ankles-balance-workout/",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 37,
    "name": "Mini Band Biceps Curl (stojąc)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtrainfitness.com/24-mini-band-exercises-chest-back-shoulders-arms-core-glutes-hips-legs-ankles-balance-workout/",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 38,
    "name": "Half-Kneeling Bicep Curl (uginanie ramienia w polklęku) z guma pod stopa",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=sdft3ga7Hx0&t=267s",
    "isYoutube": true,
    "videoId": "sdft3ga7Hx0",
    "start": 267,
    "done": false
  },
  {
    "id": 39,
    "name": "Mini Band Triceps Pushdown",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtrainfitness.com/24-mini-band-exercises-chest-back-shoulders-arms-core-glutes-hips-legs-ankles-balance-workout/",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 40,
    "name": "Standing Narrow Tricep Extension (wąski wyprost triceps) z guma - druga wersja 71 (tam bokiem, tu prosto)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=sdft3ga7Hx0&t=420s",
    "isYoutube": true,
    "videoId": "sdft3ga7Hx0",
    "start": 420,
    "done": false
  },
  {
    "id": 41,
    "name": "Triceps tyłem (do góry)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=sdft3ga7Hx0&t=572s",
    "isYoutube": true,
    "videoId": "sdft3ga7Hx0",
    "start": 572,
    "done": false
  },
  {
    "id": 42,
    "name": "Triceps tyłem (do dołu)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=sdft3ga7Hx0&t=572s",
    "isYoutube": true,
    "videoId": "sdft3ga7Hx0",
    "start": 572,
    "done": false
  },
  {
    "id": 43,
    "name": "Low Pull-Apart (rozciąganie gumy nisko) - początkujący",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Lk5PisETE9I&t=144s",
    "isYoutube": true,
    "videoId": "Lk5PisETE9I",
    "start": 144,
    "done": false
  },
  {
    "id": 44,
    "name": "Double Lateral Triceps Extension (wyprost triceps obiema rękami) TRUDNIEJSZA WERSJA 82",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=H78qhvplQFU&t=797s",
    "isYoutube": true,
    "videoId": "H78qhvplQFU",
    "start": 797,
    "done": false
  },
  {
    "id": 45,
    "name": "Lateral Triceps Extension (wyprost triceps na boki)",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=H78qhvplQFU&t=85s",
    "isYoutube": true,
    "videoId": "H78qhvplQFU",
    "start": 85,
    "done": false
  },
  {
    "id": 46,
    "name": "Straight Arm Pulse Raise (pulsujące unoszenie prostej ręki) z bandem",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=e90l8zQtXbc&t=254s",
    "isYoutube": true,
    "videoId": "e90l8zQtXbc",
    "start": 254,
    "done": false
  },
  {
    "id": 47,
    "name": "Lat pull down",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Mw5C4WTHEVE&t=240s",
    "isYoutube": true,
    "videoId": "Mw5C4WTHEVE",
    "start": 240,
    "done": false
  },
  {
    "id": 48,
    "name": "Archer Row / T-Row (wiosłowanie typu \"lucznik\") - TO CO 23 STOJĄC",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=H78qhvplQFU&t=1114s",
    "isYoutube": true,
    "videoId": "H78qhvplQFU",
    "start": 1114,
    "done": false
  },
  {
    "id": 49,
    "name": "Half-Kneeling Archer Row",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=B6bAgIz9uFw",
    "isYoutube": true,
    "videoId": "B6bAgIz9uFw",
    "start": 0,
    "done": false
  },
  {
    "id": 50,
    "name": "Serve the Platter (unoszenie ręki jak z tacka) z bandem",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=e90l8zQtXbc&t=463s",
    "isYoutube": true,
    "videoId": "e90l8zQtXbc",
    "start": 463,
    "done": false
  },
  {
    "id": 51,
    "name": "SeatedRow - \"Teros\" (wiosłowanie oburącz) - RĘCE WEWNĄTRZ",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=DPZJ_HuF6lE&t=1260s",
    "isYoutube": true,
    "videoId": "DPZJ_HuF6lE",
    "start": 1260,
    "done": false
  },
  {
    "id": 52,
    "name": "SeatedRow - \"Teros\" (wiosłowanie oburącz) - GUMA ROZCIĄGNIĘTA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=DPZJ_HuF6lE&t=1260s",
    "isYoutube": true,
    "videoId": "DPZJ_HuF6lE",
    "start": 1260,
    "done": false
  },
  {
    "id": 53,
    "name": "Single Arm Row (wiosłowanie jednorecz) z bandem zaczepionym o stopę",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=_xrAGY9ST4g&t=518s",
    "isYoutube": true,
    "videoId": "_xrAGY9ST4g",
    "start": 518,
    "done": false
  },
  {
    "id": 54,
    "name": "Mini Band Wall Slide - SIŁOWNIA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Silownia",
    "link": "https://www.youtube.com/shorts/wAb_LNjfnIw",
    "isYoutube": true,
    "videoId": "wAb_LNjfnIw",
    "start": 0,
    "done": false
  },
  {
    "id": 55,
    "name": "Mini Band Wall Slide tyłem - SIŁOWNIA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Silownia",
    "link": "https://www.youtube.com/watch?v=wLlqzWMHrXI",
    "isYoutube": true,
    "videoId": "wLlqzWMHrXI",
    "start": 0,
    "done": false
  },
  {
    "id": 56,
    "name": "Wall clock SIŁOWNIA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Silownia",
    "link": "https://www.tiktok.com/@theprehabguys/video/7251292069937958187",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 57,
    "name": "Spider crawls SIŁOWNIA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Silownia",
    "link": "https://www.tiktok.com/@make.it.train/video/7313010368345885995",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 58,
    "name": "1 SIŁOWNIA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Silownia",
    "link": "https://www.tiktok.com/@fizjoboryss/video/7623838617907121441",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 59,
    "name": "2 SIŁOWNIA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Silownia",
    "link": "https://www.tiktok.com/@fizjoboryss/video/7623838617907121441",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 60,
    "name": "3 SIŁOWNIA",
    "partia": "Gorna",
    "sprzet": "Mini band",
    "miejsce": "Silownia",
    "link": "https://www.tiktok.com/@fizjoboryss/video/7623838617907121441",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 61,
    "name": "Uginanie nogi w kolanie z bandem (biceps uda)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=zDA3e3oYIg4&t=417s",
    "isYoutube": true,
    "videoId": "zDA3e3oYIg4",
    "start": 417,
    "done": false
  },
  {
    "id": 62,
    "name": "Hip Bridge Single Leg Extension (mostek z wyprostem jednej nogi) z mini bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=yCTo7Hs03mo&t=86s",
    "isYoutube": true,
    "videoId": "yCTo7Hs03mo",
    "start": 86,
    "done": false
  },
  {
    "id": 63,
    "name": "Toe-Tap/Leg Extension w tabletop (uginanie-prostowanie nog) z guma na stopach",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=pw5qYP3Gz0k&t=692s",
    "isYoutube": true,
    "videoId": "pw5qYP3Gz0k",
    "start": 692,
    "done": false
  },
  {
    "id": 64,
    "name": "Wall Sit (przysiad przy scianie) z bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=DPZJ_HuF6lE&t=349s",
    "isYoutube": true,
    "videoId": "DPZJ_HuF6lE",
    "start": 349,
    "done": false
  },
  {
    "id": 65,
    "name": "Squat + Calf Raise Combo (przysiad z wspieciem na palce)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=DPZJ_HuF6lE&t=2419s",
    "isYoutube": true,
    "videoId": "DPZJ_HuF6lE",
    "start": 2419,
    "done": false
  },
  {
    "id": 66,
    "name": "Low Squat Shuffle (przemieszczanie w niskim przysiadzie) z mini bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Qh_sBoA9Doo&t=498s",
    "isYoutube": true,
    "videoId": "Qh_sBoA9Doo",
    "start": 498,
    "done": false
  },
  {
    "id": 67,
    "name": "Pulse Squat z podwojnym pulsem z bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=gm4zVOaj37E&t=635s",
    "isYoutube": true,
    "videoId": "gm4zVOaj37E",
    "start": 635,
    "done": false
  },
  {
    "id": 68,
    "name": "Squat Sidestep Ladder (drabinka: przysiad + krok w bok) z bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=y-nbg7vNkcY&t=220s",
    "isYoutube": true,
    "videoId": "y-nbg7vNkcY",
    "start": 220,
    "done": false
  },
  {
    "id": 69,
    "name": "Squat Walk (marsz w przysiadzie) z mini bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Qh_sBoA9Doo&t=842s",
    "isYoutube": true,
    "videoId": "Qh_sBoA9Doo",
    "start": 842,
    "done": false
  },
  {
    "id": 70,
    "name": "Sumo Squat (przysiad sumo, wolne tempo) z bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=y-nbg7vNkcY&t=1560s",
    "isYoutube": true,
    "videoId": "y-nbg7vNkcY",
    "start": 1560,
    "done": false
  },
  {
    "id": 71,
    "name": "Gate Swings / Wide Squat Jump (wyskoki z szerokiego przysiadu)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=DPZJ_HuF6lE&t=2350s",
    "isYoutube": true,
    "videoId": "DPZJ_HuF6lE",
    "start": 2350,
    "done": false
  },
  {
    "id": 72,
    "name": "Single Leg RDL Ladder (martwy ciag rumuński jednonóż - drabinka) z bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=y-nbg7vNkcY&t=353s",
    "isYoutube": true,
    "videoId": "y-nbg7vNkcY",
    "start": 353,
    "done": false
  },
  {
    "id": 73,
    "name": "Standing Back Extension / Stiff-Leg Deadlift (wyprost tułowia na sztywnych nogach)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=DPZJ_HuF6lE&t=1181s",
    "isYoutube": true,
    "videoId": "DPZJ_HuF6lE",
    "start": 1181,
    "done": false
  },
  {
    "id": 74,
    "name": "Hip Abductor leżąc (otwieranie nog jak na maszynie) z bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=k2vk-UIxZE4&t=550s",
    "isYoutube": true,
    "videoId": "k2vk-UIxZE4",
    "start": 550,
    "done": false
  },
  {
    "id": 75,
    "name": "Hip Bridge Push-Apart (mostek z rozpychaniem kolan) z mini bandem JEDNONOŻ UNOSZENIE",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=yCTo7Hs03mo&t=72s",
    "isYoutube": true,
    "videoId": "yCTo7Hs03mo",
    "start": 72,
    "done": false
  },
  {
    "id": 76,
    "name": "Fast feet",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=DPZJ_HuF6lE&t=81s",
    "isYoutube": true,
    "videoId": "DPZJ_HuF6lE",
    "start": 81,
    "done": false
  },
  {
    "id": 77,
    "name": "Lateral Tippy-Toe Walk Ladder (drabinka boczna na palcach) z mini bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=yCTo7Hs03mo&t=720s",
    "isYoutube": true,
    "videoId": "yCTo7Hs03mo",
    "start": 720,
    "done": false
  },
  {
    "id": 78,
    "name": "Single Leg Backward Step Load (obciążenie tylne jednej nogi) z mini bandem na kostkach KROKI",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=yCTo7Hs03mo&t=494s",
    "isYoutube": true,
    "videoId": "yCTo7Hs03mo",
    "start": 494,
    "done": false
  },
  {
    "id": 79,
    "name": "Single Leg Lateral Step Load (obciążenie boczne jednej nogi) z mini bandem na kostkach KROKI",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=yCTo7Hs03mo&t=415s",
    "isYoutube": true,
    "videoId": "yCTo7Hs03mo",
    "start": 415,
    "done": false
  },
  {
    "id": 80,
    "name": "Miesień obszerny boczny (w planku)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=k2vk-UIxZE4&t=609s",
    "isYoutube": true,
    "videoId": "k2vk-UIxZE4",
    "start": 609,
    "done": false
  },
  {
    "id": 81,
    "name": "Lateral Walks - marsz boczny oraz przód-tył z mini bandem NAD KOSTKAMI",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=3cVg-kNJKMw&t=326s",
    "isYoutube": true,
    "videoId": "3cVg-kNJKMw",
    "start": 326,
    "done": false
  },
  {
    "id": 82,
    "name": "Lateral Walks - marsz boczny oraz przód-tył z mini bandem NAD KOLANAMI",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=3cVg-kNJKMw&t=326s",
    "isYoutube": true,
    "videoId": "3cVg-kNJKMw",
    "start": 326,
    "done": false
  },
  {
    "id": 83,
    "name": "Monster Walk NAD KOSTKAMI",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=snbNxUIUQPc",
    "isYoutube": true,
    "videoId": "snbNxUIUQPc",
    "start": 0,
    "done": false
  },
  {
    "id": 84,
    "name": "Monster Walk NAD KOLANAMI",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=snbNxUIUQPc",
    "isYoutube": true,
    "videoId": "snbNxUIUQPc",
    "start": 0,
    "done": false
  },
  {
    "id": 85,
    "name": "Rainbow (teczka) z bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=umUtH9gZIfc&t=339s",
    "isYoutube": true,
    "videoId": "umUtH9gZIfc",
    "start": 339,
    "done": false
  },
  {
    "id": 86,
    "name": "Standing Leg Circles (koła noga w stanie stojącym) przy podporze",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=_3NCDf7pplc&t=104s",
    "isYoutube": true,
    "videoId": "_3NCDf7pplc",
    "start": 104,
    "done": false
  },
  {
    "id": 87,
    "name": "Glute Hold (izometryczne wytrzymanie) z bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=_3NCDf7pplc&t=1206s",
    "isYoutube": true,
    "videoId": "_3NCDf7pplc",
    "start": 1206,
    "done": false
  },
  {
    "id": 88,
    "name": "Glute Jacks (pajacyki pośladkowe) z bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=_3NCDf7pplc&t=1156s",
    "isYoutube": true,
    "videoId": "_3NCDf7pplc",
    "start": 1156,
    "done": false
  },
  {
    "id": 89,
    "name": "Glute Tap (klepanie pośladków) z bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=umUtH9gZIfc&t=629s",
    "isYoutube": true,
    "videoId": "umUtH9gZIfc",
    "start": 629,
    "done": false
  },
  {
    "id": 90,
    "name": "Single Leg Bridge / Boczny Glute Lift z bandem noga do boku",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=gm4zVOaj37E&t=448s",
    "isYoutube": true,
    "videoId": "gm4zVOaj37E",
    "start": 448,
    "done": false
  },
  {
    "id": 91,
    "name": "Glute Bridge Abduction (mostek z odwiedzeniem) z bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=_3NCDf7pplc&t=504s",
    "isYoutube": true,
    "videoId": "_3NCDf7pplc",
    "start": 504,
    "done": false
  },
  {
    "id": 92,
    "name": "Glute Kickback Pulse (pulsujące wyprosty biodra) na macie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=_3NCDf7pplc&t=204s",
    "isYoutube": true,
    "videoId": "_3NCDf7pplc",
    "start": 204,
    "done": false
  },
  {
    "id": 93,
    "name": "Reverse Bridge / Hip Thrust bez ławki z bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=QG3TAwfo9iQ&t=487s",
    "isYoutube": true,
    "videoId": "QG3TAwfo9iQ",
    "start": 487,
    "done": false
  },
  {
    "id": 94,
    "name": "Scissors (nozyce) z mini bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=3cVg-kNJKMw&t=180s",
    "isYoutube": true,
    "videoId": "3cVg-kNJKMw",
    "start": 180,
    "done": false
  },
  {
    "id": 95,
    "name": "Hip Bridge March (mostek z marszem) z bandem na stopach",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=yCTo7Hs03mo&t=112s",
    "isYoutube": true,
    "videoId": "yCTo7Hs03mo",
    "start": 112,
    "done": false
  },
  {
    "id": 96,
    "name": "Three-Way Kick Sequence (kopnięcia przód-bok-tył) z guma na kostkach",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=EQio6nzPLPw&t=109s",
    "isYoutube": true,
    "videoId": "EQio6nzPLPw",
    "start": 109,
    "done": false
  },
  {
    "id": 97,
    "name": "Bent Leg Lift and Extend na czworaka z mini bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Qh_sBoA9Doo&t=1315s",
    "isYoutube": true,
    "videoId": "Qh_sBoA9Doo",
    "start": 1315,
    "done": false
  },
  {
    "id": 98,
    "name": "Front-Side-Back Leg Lift (unoszenie nogi przód-bok-tył) z mini bandem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Qh_sBoA9Doo&t=194s",
    "isYoutube": true,
    "videoId": "Qh_sBoA9Doo",
    "start": 194,
    "done": false
  },
  {
    "id": 99,
    "name": "Leg Flutter (nozycowanie) leżąc z bandem (DAĆ DWIE GUMY)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=_3NCDf7pplc&t=1106s",
    "isYoutube": true,
    "videoId": "_3NCDf7pplc",
    "start": 1106,
    "done": false
  },
  {
    "id": 100,
    "name": "Leg Lifts w podporze (plank) z bandem GUMA UDA",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=_3NCDf7pplc&t=754s",
    "isYoutube": true,
    "videoId": "_3NCDf7pplc",
    "start": 754,
    "done": false
  },
  {
    "id": 101,
    "name": "Leg Lifts w podporze (plank) z bandem GUMA KOSTKI",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=_3NCDf7pplc&t=754s",
    "isYoutube": true,
    "videoId": "_3NCDf7pplc",
    "start": 754,
    "done": false
  },
  {
    "id": 102,
    "name": "Side-Lying Leg Lift Series z guma na udach (łatwiejsze niz plank)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=pw5qYP3Gz0k&t=1664s",
    "isYoutube": true,
    "videoId": "pw5qYP3Gz0k",
    "start": 1664,
    "done": false
  },
  {
    "id": 103,
    "name": "Kopnięcie po przekątnej do przodu",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=zDA3e3oYIg4&t=123s",
    "isYoutube": true,
    "videoId": "zDA3e3oYIg4",
    "start": 123,
    "done": false
  },
  {
    "id": 104,
    "name": "Kopnięcie po przekątnej do tyłu",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=zDA3e3oYIg4&t=142s",
    "isYoutube": true,
    "videoId": "zDA3e3oYIg4",
    "start": 142,
    "done": false
  },
  {
    "id": 105,
    "name": "Rotacja zewnętrzna biodra na stojaco (otwieranie bioder)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=zDA3e3oYIg4&t=462s",
    "isYoutube": true,
    "videoId": "zDA3e3oYIg4",
    "start": 462,
    "done": false
  },
  {
    "id": 106,
    "name": "Band Clamshell (stopy złączone)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=m_ZPapmqeNM",
    "isYoutube": true,
    "videoId": "m_ZPapmqeNM",
    "start": 0,
    "done": false
  },
  {
    "id": 107,
    "name": "Band Seated Hip Abduction",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=NeO0w4Jv4rs",
    "isYoutube": true,
    "videoId": "NeO0w4Jv4rs",
    "start": 0,
    "done": false
  },
  {
    "id": 108,
    "name": "Banded Frog Pumps",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=rzjQ8XpXt1Q",
    "isYoutube": true,
    "videoId": "rzjQ8XpXt1Q",
    "start": 0,
    "done": false
  },
  {
    "id": 109,
    "name": "Band Hip Thrust with Hip Abduction",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=HZ0vjMAmpfI",
    "isYoutube": true,
    "videoId": "HZ0vjMAmpfI",
    "start": 0,
    "done": false
  },
  {
    "id": 110,
    "name": "Hip Internal/External Rotation (mini band)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://youtube.com/watch?v=PzWue7bprsE",
    "isYoutube": true,
    "videoId": "PzWue7bprsE",
    "start": 0,
    "done": false
  },
  {
    "id": 111,
    "name": "Mini-Band Knee Rotations",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=ch2ZYj0qSFE",
    "isYoutube": true,
    "videoId": "ch2ZYj0qSFE",
    "start": 0,
    "done": false
  },
  {
    "id": 112,
    "name": "Mini Band Ankle Inversion",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=SURgyndoyV8",
    "isYoutube": true,
    "videoId": "SURgyndoyV8",
    "start": 0,
    "done": false
  },
  {
    "id": 113,
    "name": "Mini Band Ankle Eversion",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=BbdMnfz2xpA",
    "isYoutube": true,
    "videoId": "BbdMnfz2xpA",
    "start": 0,
    "done": false
  },
  {
    "id": 114,
    "name": "Mini Band Ankle Dorsiflexion",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Lh1drmQL5Xw",
    "isYoutube": true,
    "videoId": "Lh1drmQL5Xw",
    "start": 0,
    "done": false
  },
  {
    "id": 115,
    "name": "Mini Band Ankle Plantar Flexion",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=0pBccIVQk2M",
    "isYoutube": true,
    "videoId": "0pBccIVQk2M",
    "start": 0,
    "done": false
  },
  {
    "id": 116,
    "name": "Standing Fire Hydrants",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=v3Sc-VjWK3A&t=25s",
    "isYoutube": true,
    "videoId": "v3Sc-VjWK3A",
    "start": 25,
    "done": false
  },
  {
    "id": 117,
    "name": "Podnoszenie kolan w staniu (guma, PL)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://spilkarza.pl/trening-z-gumami-oporowymi-15-cwiczen-dla-pilkarza/",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 118,
    "name": "Przysiad boczny (PL) GUMA NA KOSTKACH",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=I_iGpMMgpC4",
    "isYoutube": true,
    "videoId": "I_iGpMMgpC4",
    "start": 0,
    "done": false
  },
  {
    "id": 119,
    "name": "Przysiad boczny (PL) GUMA NAD UDAMI",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=I_iGpMMgpC4",
    "isYoutube": true,
    "videoId": "I_iGpMMgpC4",
    "start": 0,
    "done": false
  },
  {
    "id": 120,
    "name": "Mini Loop Band Lunge",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://fitbod.me/exercises/mini-loop-band-lunge",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 121,
    "name": "Mini Loop Band Jump Squat",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://fitbod.me/exercises/mini-loop-band-jump-squat",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 122,
    "name": "Mini Loop Band Alternating Leg Raises",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://fitbod.me/exercises/mini-loop-band-alternating-leg-raises",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 123,
    "name": "Unoszenie jednej nogi w góre leżąc, druga leży (jak mobility)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://fitbod.me/exercises/mini-loop-band-alternating-leg-raises",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 124,
    "name": "Banded Curtsy Lunge",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://fitbod.me/exercises/banded-curtsy-lunge",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 125,
    "name": "Mini Loop Band Single Leg RDL with Row",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://fitbod.me/exercises/mini-loop-band-single-leg-romanian-deadlift-with-row",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 126,
    "name": "Mini Loop Band Side-Lying Hip Abduction",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://fitbod.me/exercises/mini-loop-band-side-lying-hip-abduction",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 127,
    "name": "Mini Loop Band Side-Plank Hip Abduction (KOSTKI)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://fitbod.me/exercises/mini-loop-band-side-lying-hip-abduction",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 128,
    "name": "Mini Loop Band Side-Plank Hip Abduction (UDA)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://fitbod.me/exercises/mini-loop-band-side-lying-hip-abduction",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 129,
    "name": "Mini Loop Band Fire Hydrant Circle",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://fitbod.me/exercises/mini-loop-band-fire-hydrant-circle",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 130,
    "name": "Mini Loop Band Fire Hydrant",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://fitbod.me/exercises/mini-loop-band-fire-hydrant",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 131,
    "name": "Mini Loop Band Glute Thrust",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://fitbod.me/exercises/mini-loop-band-glute-thrust",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 132,
    "name": "Mini Loop Band Lunge Kickback",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://fitbod.me/exercises/mini-loop-band-lunge-kickback",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 133,
    "name": "Jaskółka z gumą (odmiana martwego ciągu trudniejsza)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=_PGc9K7UMI4",
    "isYoutube": true,
    "videoId": "_PGc9K7UMI4",
    "start": 0,
    "done": false
  },
  {
    "id": 134,
    "name": "Banded Glute Bridge with Alternating Leg Raise",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://fitbod.me/exercises/banded-glute-bridge-with-alternating-leg-raise",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 135,
    "name": "Hip Bridge with Band Resisted Marching",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=NWqR3V8aMlk",
    "isYoutube": true,
    "videoId": "NWqR3V8aMlk",
    "start": 0,
    "done": false
  },
  {
    "id": 136,
    "name": "Long Lever Bridge with Band Resisted Marching",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=mb1yKDwyHCk",
    "isYoutube": true,
    "videoId": "mb1yKDwyHCk",
    "start": 0,
    "done": false
  },
  {
    "id": 137,
    "name": "Bird Dog with Resisted Hip Extension",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=WW_3LpvtHsY",
    "isYoutube": true,
    "videoId": "WW_3LpvtHsY",
    "start": 0,
    "done": false
  },
  {
    "id": 138,
    "name": "Single Leg Stance with Hip Abduction",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=wSOAfr0df3w",
    "isYoutube": true,
    "videoId": "wSOAfr0df3w",
    "start": 0,
    "done": false
  },
  {
    "id": 139,
    "name": "Plank Lateral Taps",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=Mim3NXbYG4w&pp=ygUcUGxhbmsgTGF0ZXJhbCBUYXBzIG1pbmkgYmFuZA%3D%3D",
    "isYoutube": true,
    "videoId": "Mim3NXbYG4w",
    "start": 0,
    "done": false
  },
  {
    "id": 140,
    "name": "Vertical scissors (na boki)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": null,
    "isYoutube": false,
    "videoId": null,
    "start": 0,
    "done": false
  },
  {
    "id": 141,
    "name": "Leżąc scissors (na boki)",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": null,
    "isYoutube": false,
    "videoId": null,
    "start": 0,
    "done": false
  },
  {
    "id": 142,
    "name": "Reverse Lunge",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.youtube.com/watch?v=qmla29NY750",
    "isYoutube": true,
    "videoId": "qmla29NY750",
    "start": 0,
    "done": false
  },
  {
    "id": 143,
    "name": "czwarte cwiczenie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DaIlkkLC0j5/?stkn=MWtheTFtdHh3bjZ0dg==",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 144,
    "name": "czwarte cwiczenie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DbvbkXcyXBQ/?stkn=MWUybHNrcnBiemxuMQ==",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 145,
    "name": "pierwsze ćwiczenie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DYryXbsR6Sb/?stkn=amxnaG9mMzk0ODkz",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 146,
    "name": "trzecie ćwiczenie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DYryXbsR6Sb/?stkn=amxnaG9mMzk0ODkz",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 147,
    "name": "czwarte ćwiczenie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DYryXbsR6Sb/?stkn=amxnaG9mMzk0ODkz",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 148,
    "name": "trzecie ćwiczenie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/Db3v7ElIBGn/?stkn=cGY2bXJ3eDVhaWs3",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 149,
    "name": "piąte ćwiczenie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/Db3v7ElIBGn/?stkn=cGY2bXJ3eDVhaWs3",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 150,
    "name": "pierwsze",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DbDCdaUsW_K/?stkn=MTR0OXlicml4ZWx2eg==",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 151,
    "name": "drugie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DbDCdaUsW_K/?stkn=MTR0OXlicml4ZWx2eg==",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 152,
    "name": "trzecie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DbDCdaUsW_K/?stkn=MTR0OXlicml4ZWx2eg==",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 153,
    "name": "pierwsze",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DawOnBYtyg9/?stkn=b3k1bXJ3cnA5bmVp",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 154,
    "name": "drugie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DawOnBYtyg9/?stkn=b3k1bXJ3cnA5bmVp",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 155,
    "name": "trzecie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DawOnBYtyg9/?stkn=b3k1bXJ3cnA5bmVp",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 156,
    "name": "uderzenie wewnętrzną",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/Dbiy5FkIIj5/?stkn=MTIyZjFyZGNyZTNwMA==",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 157,
    "name": "Pierwsze",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DbV244JxYVL/?stkn=OG1majJqZHprbG5j",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 158,
    "name": "drugie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DbV244JxYVL/?stkn=OG1majJqZHprbG5j",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 159,
    "name": "trzecie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DbV244JxYVL/?stkn=OG1majJqZHprbG5j",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 160,
    "name": "pierwsze ",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DaxjQ-vOC5u/?stkn=OGRic2tqM3UxbGdn",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 161,
    "name": "drugie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DaxjQ-vOC5u/?stkn=OGRic2tqM3UxbGdn",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 162,
    "name": "czwarte",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DaxjQ-vOC5u/?stkn=OGRic2tqM3UxbGdn",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 163,
    "name": "Pierwsze",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/p/DcLwaDOCNaS/?img_index=3&stkn=Zms4YTluZDJjMDNj",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 164,
    "name": "trzecie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/p/DcLwaDOCNaS/?img_index=3&stkn=Zms4YTluZDJjMDNj",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 165,
    "name": "drugie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/p/DcJDtgUCPiX/?img_index=6&stkn=MWRsN2MycjE4cWx3Nw==",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 166,
    "name": "szybka noga",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DcJK1_Asc3P/?stkn=MWNuN2NlaTZuemt5OA==",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 167,
    "name": "trzecie na kostke",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DcOAtV7IJqk/?stkn=MWx2eTZ2bDd3dnVhOQ==",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 168,
    "name": "szóste ",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DZxCLMPS3KH/?stkn=MXF4Z2puYzRmeTJkMA==",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 169,
    "name": "cztery",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/p/DcixcsKiArg/?img_index=4&stkn=MTlhdnd1bjBlbTd4Ng==",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 170,
    "name": "piec",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/p/DcixcsKiArg/?img_index=4&stkn=MTlhdnd1bjBlbTd4Ng==",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 171,
    "name": "pierwsze",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DcUpO_Zt68Z/?stkn=bmgzd21mMXpwOXB3",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 172,
    "name": "czwarte",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DcUpO_Zt68Z/?stkn=bmgzd21mMXpwOXB3",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 173,
    "name": "polprzysiad z podskokiem",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DcgnDmjINS4/?stkn=bHBmYWo3Nm4weHdu",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 174,
    "name": "Ostatnie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/DcbjCiDokaR/?stkn=MXRwZmN3NWVsZ3A1NQ==",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 175,
    "name": "pierwsze",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/Dcsx4pfIse-/?stkn=cWV5anB5YzNsdXFq",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 176,
    "name": "drugie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/Dcsx4pfIse-/?stkn=cWV5anB5YzNsdXFq",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 177,
    "name": "trzecie",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/Dcsx4pfIse-/?stkn=cWV5anB5YzNsdXFq",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 178,
    "name": "czwarte",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/Dcsx4pfIse-/?stkn=cWV5anB5YzNsdXFq",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 179,
    "name": "Piątek",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/Dcsx4pfIse-/?stkn=cWV5anB5YzNsdXFq",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  },
  {
    "id": 180,
    "name": "szóste",
    "partia": "Dolna",
    "sprzet": "Mini band",
    "miejsce": "Dowolnie",
    "link": "https://www.instagram.com/reel/Dcsx4pfIse-/?stkn=cWV5anB5YzNsdXFq",
    "isYoutube": false,
    "videoId": null,
    "start": null,
    "done": false
  }
];
